consul:
  image: progrium/consul
  container_name: consul
  restart: always
  ports:
    - "8400:8400"
    - "8500:8500"
    - "8600:53/udp"
  command: -server -bootstrap
registrator:
  image: gliderlabs/registrator
  container_name: registrator
  restart: always
  net: host
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock
  command: consul://<consul_ip>:8500
swarm-agent:
  image: swarm
  container_name: swarm-agent
  command: join --advertise=<node_ip>:2375 consul://<consul_ip>:8500/nodes
swarm-manager:
  image: swarm
  container_name: swarm-manager
  labels:
  - "SERVICE_4000_NAME=swarm-manager"
  - "SERVICE_4000_CHECK_HTTP=http://$SERVICE_IP:4000"
  command: manage -H :4000 --replication --advertise <node_ip>:4000 consul://<consul_ip>:8500/nodes
  ports:
    - "4000:4000"
